name:                unveil
version:             0.1.0.0
github:              "amakuri/unveil"
license:             BSD3
author:              "amakuri"
maintainer:          "makuri@makuri.world"
copyright:           "Copyright (c) 2018 amakuri"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on Github at <https://github.com/amakuri/unveil#readme>

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: source
  default-extensions:
    - OverloadedStrings
    - RankNTypes
    - TemplateHaskell
    - QuasiQuotes
    - FlexibleContexts
  dependencies:
    - optparse-applicative
    - ansi-terminal
    - terminal-size
    - lens
    - text
    - hidden-char
    - path
    - path-io
    - mtl
    - bytestring
    - yaml
    - aeson


executables:
  unveil:
    main:                Main.hs
    source-dirs:         main
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - unveil
    - mtl

tests:
  unveil-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - unveil
